/*
public class ExemploExcecao {
    public static void main(String[] args) {
        try {
            int resultado = 10 / 0; // Isso causará uma ArithmeticException
        } catch (ArithmeticException e) {
            System.out.println("Erro: Divisão por zero.");
        } finally {
            System.out.println("Bloco finally sempre é executado.");
        }
    }
}
*/